name: d_encrypt
description: A starting point for Dart libraries or applications.
version: 0.0.1

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.1
  cryptography: ^2.0.1
  ninja_prime:
    git: https://github.com/Parkar99/prime.git

dev_dependencies:
  lint: ^1.5.3
  test: ^1.17.3
